import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

/**
 * Generates a bank-ready PDF report for financial documentation.
 * @param {object} data - The report data object.
 */
export function generateBankPDF(data = {}) {
  const doc = new jsPDF();
  const {
    farmerName = "Farmer",
    cropType = "N/A",
    landArea = "N/A",
    season = "N/A",
    estimatedRevenue = 0,
    estimatedCost = 0,
    netProfit = 0,
    riskLevel = "Low",
    date = new Date().toLocaleDateString("en-IN"),
  } = data;

  // Header
  doc.setFillColor(22, 163, 74);
  doc.rect(0, 0, 210, 30, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("Fasal Saathi — Agricultural Bank Report", 14, 18);

  // Subtitle
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`Generated on: ${date}`, 14, 26);

  // Farmer Details Section
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(13);
  doc.setFont("helvetica", "bold");
  doc.text("Farmer Profile", 14, 44);

  autoTable(doc, {
    startY: 48,
    head: [["Field", "Details"]],
    body: [
      ["Farmer Name", farmerName],
      ["Primary Crop", cropType],
      ["Land Area", `${landArea} acres`],
      ["Season", season],
      ["Report Date", date],
    ],
    headStyles: { fillColor: [22, 163, 74] },
    styles: { fontSize: 11 },
  });

  // Financial Summary Section
  const afterFarmerTable = doc.lastAutoTable.finalY + 10;
  doc.setFontSize(13);
  doc.setFont("helvetica", "bold");
  doc.text("Financial Summary", 14, afterFarmerTable);

  autoTable(doc, {
    startY: afterFarmerTable + 4,
    head: [["Metric", "Amount (INR)"]],
    body: [
      ["Estimated Revenue", `₹ ${Number(estimatedRevenue).toLocaleString("en-IN")}`],
      ["Estimated Cost", `₹ ${Number(estimatedCost).toLocaleString("en-IN")}`],
      ["Net Profit", `₹ ${Number(netProfit).toLocaleString("en-IN")}`],
      ["Risk Level", riskLevel],
    ],
    headStyles: { fillColor: [22, 163, 74] },
    bodyStyles: { fontSize: 11 },
    didParseCell(hookData) {
      if (hookData.row.index === 2 && hookData.column.index === 1) {
        hookData.cell.styles.textColor =
          netProfit >= 0 ? [22, 163, 74] : [220, 38, 38];
        hookData.cell.styles.fontStyle = "bold";
      }
    },
  });

  // Footer
  const pageHeight = doc.internal.pageSize.height;
  doc.setFontSize(9);
  doc.setTextColor(120, 120, 120);
  doc.text(
    "This report is generated by Fasal Saathi for informational purposes only. Please consult a registered financial advisor for official loan applications.",
    14,
    pageHeight - 14,
    { maxWidth: 182 }
  );

  doc.save(`FasalSaathi_BankReport_${farmerName.replace(/\s+/g, "_")}_${date.replace(/\//g, "-")}.pdf`);
}

/**
 * Generates and downloads a CSV file from the report data.
 * @param {object} data - The report data object.
 */
export function generateCSV(data = {}) {
  const {
    farmerName = "Farmer",
    cropType = "N/A",
    landArea = "N/A",
    season = "N/A",
    estimatedRevenue = 0,
    estimatedCost = 0,
    netProfit = 0,
    riskLevel = "Low",
    date = new Date().toLocaleDateString("en-IN"),
  } = data;

  const rows = [
    ["Fasal Saathi - Agricultural Financial Report"],
    [""],
    ["Field", "Value"],
    ["Farmer Name", farmerName],
    ["Primary Crop", cropType],
    ["Land Area (acres)", landArea],
    ["Season", season],
    ["Report Date", date],
    [""],
    ["Financial Metric", "Amount (INR)"],
    ["Estimated Revenue", estimatedRevenue],
    ["Estimated Cost", estimatedCost],
    ["Net Profit", netProfit],
    ["Risk Level", riskLevel],
  ];

  const csvContent = rows
    .map((row) => row.map((cell) => `"${cell}"`).join(","))
    .join("\n");

  const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.setAttribute(
    "download",
    `FasalSaathi_Report_${farmerName.replace(/\s+/g, "_")}.csv`
  );
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
