import jsPDF from "jspdf";
import "jspdf-autotable";

/**
 * Generates a professional Bank Report PDF for the farmer.
 * @param {Object} data - The data to include in the report.
 */
export const generateBankPDF = (data) => {
  const { farmerName, location, reputation, riskIndex, financialData, date } = data;
  const doc = new jsPDF();
  const primaryColor = [22, 163, 74]; // #16a34a

  // Header
  doc.setFillColor(...primaryColor);
  doc.rect(0, 0, 210, 40, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.text("Fasal Saathi - Bank Report", 20, 25);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`Generated on: ${date}`, 160, 25);

  // Farmer Information Section
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Farmer Profile", 20, 55);
  doc.setLineWidth(0.5);
  doc.line(20, 57, 190, 57);

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  const profileInfo = [
    ["Full Name:", farmerName],
    ["Location:", location],
    ["Reputation Score:", `${reputation} Points`],
    ["Verification Status:", "Verified Farmer Expert"]
  ];

  doc.autoTable({
    startY: 62,
    body: profileInfo,
    theme: "plain",
    styles: { fontSize: 10, cellPadding: 2 },
    columnStyles: { 0: { fontStyle: "bold", width: 40 } }
  });

  // Risk Assessment Section
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Risk Index Summary", 20, doc.lastAutoTable.finalY + 15);
  doc.line(20, doc.lastAutoTable.finalY + 17, 190, doc.lastAutoTable.finalY + 17);

  const riskData = [
    ["Weather Risk", `${riskIndex.weather}%`, riskIndex.weather > 50 ? "High" : "Low"],
    ["Disease Risk", `${riskIndex.disease}%`, riskIndex.disease > 50 ? "High" : "Low"],
    ["Water Scarcity", `${riskIndex.water}%`, riskIndex.water > 50 ? "High" : "Low"],
    ["Market Volatility", `${riskIndex.market}%`, riskIndex.market > 50 ? "High" : "Low"]
  ];

  doc.autoTable({
    startY: doc.lastAutoTable.finalY + 22,
    head: [["Risk Category", "Score", "Assessment"]],
    body: riskData,
    headStyles: { fillColor: primaryColor },
    styles: { halign: "center" }
  });

  // Financial Projections Section
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Financial Projections", 20, doc.lastAutoTable.finalY + 15);
  doc.line(20, doc.lastAutoTable.finalY + 17, 190, doc.lastAutoTable.finalY + 17);

  const financialTable = [
    ["Estimated Revenue", `INR ${financialData.revenue.toLocaleString()}`],
    ["Operational Costs", `INR ${financialData.costs.toLocaleString()}`],
    ["Net Profit Margin", `INR ${financialData.profit.toLocaleString()}`],
    ["Profit Percentage", `${financialData.percentage}%`]
  ];

  doc.autoTable({
    startY: doc.lastAutoTable.finalY + 22,
    body: financialTable,
    theme: "striped",
    styles: { fontSize: 11, cellPadding: 5 },
    columnStyles: { 0: { fontStyle: "bold" }, 1: { halign: "right" } }
  });

  // Footer Disclaimer
  const pageHeight = doc.internal.pageSize.height;
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text("This report is generated by Fasal Saathi AI Advisor based on historical data and AI predictions.", 20, pageHeight - 20);
  doc.text("It is intended for informational purposes and loan eligibility assessment.", 20, pageHeight - 15);

  doc.save(`Fasal_Saathi_Bank_Report_${farmerName.replace(/\s+/g, '_')}.pdf`);
};

/**
 * Generates a CSV file from the provided data.
 */
export const generateCSV = (data) => {
  const { farmerName, riskIndex, financialData } = data;
  
  const rows = [
    ["Category", "Value"],
    ["Farmer Name", farmerName],
    ["Weather Risk", `${riskIndex.weather}%`],
    ["Disease Risk", `${riskIndex.disease}%`],
    ["Water Risk", `${riskIndex.water}%`],
    ["Market Risk", `${riskIndex.market}%`],
    ["Estimated Revenue", financialData.revenue],
    ["Operational Costs", financialData.costs],
    ["Net Profit", financialData.profit]
  ];

  let csvContent = "data:text/csv;charset=utf-8," 
    + rows.map(e => e.join(",")).join("\n");

  const encodedUri = encodeURI(csvContent);
  const link = document.createElement("a");
  link.setAttribute("href", encodedUri);
  link.setAttribute("download", `Farmer_Data_${farmerName.replace(/\s+/g, '_')}.csv`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};
